config/routes.rb
RailsInventory::Application.routes.draw do

  resources :datastorages

  resources :replace_parts

  devise_for :users

  resources :infos

  resources :commutators

  resources :wifis

  resources :servers do
    get :export, on: :collection
  end

  resources :tape_libraries

  resources :areas do
    resources :rackspaces
  end

  resources :zones

  resources :dcats do
    resources :dcat_items
  end

  resources :blades do
    resources :parts
  end

  get "history" => "history#index"

  get "main/index"
 
  

  

   root :to => 'main#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/replace_part.rb
class ReplacePart < ActiveRecord::Base
  attr_accessible :date_getting, :date_sending, :descr_getting, :descr_sending, :detail_type, :network_name
  default_scope order("created_at desc")
end

app/controllers/replace_parts_controller.rb
class ReplacePartsController < ApplicationController
  # GET /replace_parts
  # GET /replace_parts.json
  
    before_filter :set_page_title

  def set_page_title
    page_title(t(:replace_parts), "icon-truck")
  end
  
  
  
  
  def index
    @replace_parts = ReplacePart.order("created_at desc").all
	
	add_breadcrumb t :replace_parts, replace_parts_path
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @replace_parts }
    end
  end

  # GET /replace_parts/1
  # GET /replace_parts/1.json
  def show
    @replace_part = ReplacePart.find(params[:id])
	
	add_breadcrumb t(:replace_parts), replace_parts_path
    add_breadcrumb @replace_part.network_name
	

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @replace_part }
    end
  end

  # GET /replace_parts/new
  # GET /replace_parts/new.json
  def new
    @replace_part = ReplacePart.new
	
	add_breadcrumb t(:replace_parts), replace_parts_path
    add_breadcrumb t(:new_replace_parts)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @replace_part }
    end
  end

  # GET /replace_parts/1/edit
  def edit
    @replace_part = ReplacePart.find(params[:id])
	
	add_breadcrumb t(:replace_parts), replace_parts_path
    add_breadcrumb t(:edit_replace_parts)
	
  end

  # POST /replace_parts
  # POST /replace_parts.json
  def create
    @replace_part = ReplacePart.new(params[:replace_part])
	
	add_breadcrumb t(:replace_parts), replace_parts_path
    add_breadcrumb t(:new_replace_parts)

    respond_to do |format|
      if @replace_part.save
        format.html { redirect_to @replace_part, notice: 'Replace part was successfully created.' }
        format.json { render json: @replace_part, status: :created, location: @replace_part }
      else
        format.html { render action: "new" }
        format.json { render json: @replace_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /replace_parts/1
  # PUT /replace_parts/1.json
  def update
    @replace_part = ReplacePart.find(params[:id])
	
	add_breadcrumb t(:replace_parts), replace_parts_path
    add_breadcrumb t(:edit_replace_parts)

    respond_to do |format|
      if @replace_part.update_attributes(params[:replace_part])
        format.html { redirect_to @replace_part, notice: 'Replace part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @replace_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replace_parts/1
  # DELETE /replace_parts/1.json
  def destroy
    @replace_part = ReplacePart.find(params[:id])
    @replace_part.destroy

    respond_to do |format|
      format.html { redirect_to replace_parts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/replace_parts_helper.rb
module ReplacePartsHelper
end

app/views/replace_parts/_form.html.erb
<%= simple_form_for @replace_part, :html => { :class => 'form-horizontal', :autocomplete => :off } do |f| %>
<div class="row">
	<div class="col-md-6  col-md-offset-3">
		<div class="widget">
			<div class="widget-content-white glossed">
				<div class="padded">
					<%= f.input :network_name, 
									  label: 'Сетевое имя',
									  label_html: { class: 'col-md-4' },
									  :wrapper => :medium,
									  :placeholder => "OIK7T-ODUYU",
									  input_html: {class: 'form-control'}
						  %>
						  
					<%= f.input :detail_type, 
							  label: 'Тип комплектующего',
							  label_html: { class: 'col-md-4' },
							  :wrapper => :medium,
							  :placeholder => "HDD",
							  input_html: {class: 'form-control'}
				  %>	  
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<div class="widget">
			<div class="widget-content-white glossed">
				<div class="padded">
					<h3 class="form-title form-title-first">Отправляемые комплектующие</h3>
						<%= f.input :date_sending, as: :string,
										  label: 'Дата отправки',
										  placeholder: "2013-10-10",
										  label_html: { class: 'col-md-4' },
										  :wrapper => :medium,
										  input_html: {class: 'form-control datepicker'}
							  %>
						 <%= f.input :descr_sending, 
							   as: :text,
										  label: 'Описание',
										  label_html: { class: 'col-md-4' },
										  :wrapper => :medium,
										  input_html: {class: 'form-control', :rows => 7} %>
				</div>
			</div>
		</div>	
	</div>

	<div class="col-md-6">
		<div class="widget">
			<div class="widget-content-white glossed">
				<div class="padded">
					<h3 class="form-title form-title-first">Получаемые комплектующие</h3>
						<%= f.input :date_getting, as: :string,
										  label: 'Дата получения',
										  placeholder: "2013-10-10",
										  label_html: { class: 'col-md-4' },
										  :wrapper => :medium,
										  input_html: {class: 'form-control datepicker'}
							  %>
						 <%= f.input :descr_getting, 
							   as: :text,
										  label: 'Описание',
										  label_html: { class: 'col-md-4' },
										  :wrapper => :medium,
										  input_html: {class: 'form-control', :rows => 7} %>
				</div>
			</div>
		</div>	
	</div>
</div>

<div class="well">
  <div class="form-group">
    <div class="pull-right">
          <%= f.button :submit, :class => 'btn-default', :value => "Сохранить" %>
          <%= link_to t('.cancel', :default => t("helpers.links.cancel")), servers_path, :class => 'btn' %>
    </div>
  </div>
</div>
<% end %> <!-- end form -->

app/views/replace_parts/edit.html.erb
<%= render 'form' %>

app/views/replace_parts/index.html.erb
<div class="widget">
  <h3 class="section-title first-title"><i class="icon-table"></i> <%= t(:replace_parts) %></h3>
  <div class="widget-content-white glossed">
    <div class="padded">
    <table class="table table-striped table-bordered table-hover">
	  <colgroup>
        <col width="50" />
        <col width="150" />
        <col width="150" />
        <col width="250" />
        <col width="250" />
        <col width="100" />
      </colgroup>
      <thead>
        <tr>
          <th>#</th>
          <th>Наименование</th>
		  <th>Тип</th>
		  <th>Отправляемые комплектующие</th>
		  <th>Получаемые комплектующие</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
          <% @replace_parts.each_with_index do |replace_part, i| %>
            <tr>
              <td><%= i + 1  %></td>
              <td><%= link_to replace_part.network_name, replace_part_path(replace_part) %></td>
			  <td><%= replace_part.detail_type  %></td>
			  <td>
				<div><strong>Дата</strong>: <%= replace_part.date_sending %></div>
				<div><%= simple_format(replace_part.descr_sending)  %></div>
			  </td>
			  
			  <td>
				<div><strong>Дата</strong>: <%= replace_part.date_getting %></div>
				<div><%= simple_format(replace_part.descr_getting)  %></div>
			  </td>
			  
              <td class="text-right">
				<% if (current_user.is_admin?) %>
					<%= link_to raw("<i class=\"icon-pencil\"></i> edit"), edit_replace_part_path(replace_part), :class => 'btn btn-default btn-xs' %>
					<%= link_to raw("<i class=\"icon-remove\"></i>"), replace_part, :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Вы уверены?')) },
                            :class => 'btn btn-danger btn-xs' %>
				<% end %>
              </td>
            </tr>
          <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_replace_part_path,
            :class => 'btn btn-primary' %>

app/views/replace_parts/new.html.erb
<%= render 'form' %>

app/views/replace_parts/show.html.erb
<dl class="dl-horizontal">
  <dt><strong>Сетевое имя:</strong></dt>
  <dd>
    <%= @replace_part.network_name %>
  </dd>
  
  <dt><strong>Тип комплектующего:</strong></dt>
  <dd>
    <%= @replace_part.detail_type %>
  </dd>
  
  <dt><strong>Дата отправки:</strong></dt>
  <dd>
    <%= @replace_part.date_sending %>
  </dd>
  
  <dt><strong>Описание отправки:</strong></dt>
  <dd>
    <%= simple_format(@replace_part.descr_sending) %>
  </dd>
  
  
  <dt><strong>Дата получения:</strong></dt>
  <dd>
    <%= @replace_part.date_getting %>
  </dd>
  
  <dt><strong>Описание получения:</strong></dt>
  <dd>
    <%= simple_format(@replace_part.descr_getting) %>
  </dd>
 </dl>

 <div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              replace_parts_path, :class => 'btn'  %>
	
  <% if (current_user.is_admin?) %>	
	  <%= link_to t('.edit', :default => t("helpers.links.edit")),
				   edit_replace_part_path(@replace_part), :class => 'btn' %>
	  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
				  replace_part_path(@replace_part),
				  :method => 'delete',
				  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
				  :class => 'btn btn-danger' %>
  <% end %>	
</div>