config/routes.rb
RailsInventory::Application.routes.draw do

  resources :datastorages

  resources :replace_parts

  devise_for :users

  resources :infos

  resources :commutators

  resources :wifis

  resources :servers do
    get :export, on: :collection
  end

  resources :tape_libraries

  resources :areas do
    resources :rackspaces
  end

  resources :zones

  resources :dcats do
    resources :dcat_items
  end

  resources :blades do
    resources :parts
  end

  get "history" => "history#index"

  get "main/index"
 
  

  

   root :to => 'main#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/dcat.rb
class Dcat < ActiveRecord::Base
  attr_accessible :alias, :name
  has_many :DcatItems, dependent: :destroy

  validates :name, presence: true
  validates :alias, presence: true
end

app/controllers/dcats_controller.rb
class DcatsController < ApplicationController
  # GET /dcats
  # GET /dcats.json

  before_filter :set_page_title

  def set_page_title
    page_title(t(:dictionary), "icon-pencil")
  end


  def index
    @dcats = Dcat.all
    add_breadcrumb t :all_cats, dcats_path
  end

  # GET /dcats/1
  # GET /dcats/1.json
  def show
    @dcat = Dcat.find(params[:id])
    
    add_breadcrumb t(:all_cats), dcats_path
    add_breadcrumb @dcat.name

  end

  # GET /dcats/new
  # GET /dcats/new.json
  def new
    @dcat = Dcat.new
    add_breadcrumb t(:all_cats), dcats_path
    add_breadcrumb t :new_cats

  end

  # GET /dcats/1/edit
  def edit
    @dcat = Dcat.find(params[:id])
    add_breadcrumb t(:all_cats), dcats_path
    add_breadcrumb t :edit_cats

  end

  # POST /dcats
  # POST /dcats.json
  def create
    @dcat = Dcat.new(params[:dcat])
    add_breadcrumb t(:all_cats), dcats_path
    add_breadcrumb t :new_cats


    respond_to do |format|
      if @dcat.save
        format.html { redirect_to @dcat, notice: 'Dcat was successfully created.' }
        format.json { render json: @dcat, status: :created, location: @dcat }
      else
        format.html { render action: "new" }
        format.json { render json: @dcat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dcats/1
  # PUT /dcats/1.json
  def update
    @dcat = Dcat.find(params[:id])
    add_breadcrumb t(:all_cats), dcats_path
    add_breadcrumb t :edit_cats


    respond_to do |format|
      if @dcat.update_attributes(params[:dcat])
        format.html { redirect_to @dcat, notice: 'Dcat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dcat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dcats/1
  # DELETE /dcats/1.json
  def destroy
    @dcat = Dcat.find(params[:id])
    @dcat.destroy

    respond_to do |format|
      format.html { redirect_to dcats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dcats_helper.rb
module DcatsHelper
end

app/views/dcats/_form.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
	  <div class="widget">
	    <div class="widget-content-white glossed">
	      <div class="padded">
	        <%= simple_form_for @dcat, :html => { :class => 'form-horizontal' } do |f| %>
	          <h3 class="form-title form-title-first"><i class="icon-th-list"></i> <%= t(:dictionary) %></h3>

		          <%= f.input :name, 
		          						label: 'Наименование',
		          						label_html: { class: 'col-md-4' },
		          						:wrapper => :medium,
		          						input_html: {class: 'form-control'}
		          %>

	            <%= f.input :alias, 
		          						label: 'Alias',
		          						label_html: { class: 'col-md-4' },
		          						:wrapper => :medium,
		          						input_html: {class: 'form-control'}%>

	          <div class="form-group">
	            <div class="col-md-offset-4 col-md-8">
	                 	<%= f.button :submit, :value => "Сохранить", :class => 'btn-default' %>
    								<%= link_to t('.cancel', :default => t("helpers.links.cancel")), dcats_path, :class => 'btn' %>
	            </div>
	          </div>
	        <% end %> <!-- end form -->
	      </div>
	    </div>
	  </div>
	</div>
</div>

app/views/dcats/edit.html.erb
<%= render :partial => 'form' %>

app/views/dcats/index.html.erb
<div class="widget">
  <h3 class="section-title first-title"><i class="icon-table"></i> <%= t(:dictionary) %></h3>
  <div class="widget-content-white glossed">
    <div class="padded">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Наименование</th>
          <th>Alias</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
          <% @dcats.each_with_index do |dcat, i| %>
            <tr>
              <td><%= i + 1  %></td>
              <td><%= link_to dcat.name, dcat_dcat_items_path(dcat) %></td>
              <td><%= dcat.alias %></td>
              <td class="text-right">
				<% if (current_user.is_admin?) %>
					<%= link_to raw("<i class=\"icon-pencil\"></i> edit"), edit_dcat_path(dcat), :class => 'btn btn-default btn-xs' %>
					<%= link_to raw("<i class=\"icon-remove\"></i>"), dcat_path(dcat), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Вы уверены?')) },
                            :class => 'btn btn-danger btn-xs' %>
				<% end %>
              </td>
            </tr>
          <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_dcat_path,
            :class => 'btn btn-primary' %>

app/views/dcats/new.html.erb
<%= render :partial => 'form' %>

app/views/dcats/show.html.erb
<dl class="dl-horizontal">
  <dt><strong>Наименование:</strong></dt>
  <dd><%= @dcat.name %></dd>
  <dt><strong>Alias:</strong></dt>
  <dd><%= @dcat.alias %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              dcats_path, :class => 'btn'  %>
 <% if (current_user.is_admin?) %>			  
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_dcat_path(@dcat), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              dcat_path(@dcat),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
 <% end %>			  
</div>