config/routes.rb
RailsInventory::Application.routes.draw do

  resources :datastorages

  resources :replace_parts

  devise_for :users

  resources :infos

  resources :commutators

  resources :wifis

  resources :servers do
    get :export, on: :collection
  end

  resources :tape_libraries

  resources :areas do
    resources :rackspaces
  end

  resources :zones

  resources :dcats do
    resources :dcat_items
  end

  resources :blades do
    resources :parts
  end

  get "history" => "history#index"

  get "main/index"
 
  

  

   root :to => 'main#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/blocks/_breadcrumbs.html.erb
<ol class="breadcrumb">
	<% if @breadcrumbs  %>
		<% @breadcrumbs[0..-2].each do |txt, path| %>
			<li><%= link_to h(txt), path %></li>
		<% end %>
		<li class="active"><%= @breadcrumbs.last.first %></li>
	<% end %>
</ol>

app/views/layouts/blocks/_footer.html.erb
	</body>
</html>

app/views/layouts/blocks/_messages.html.erb
<% if flash.count > 0
     flash.each do |name, message| %>
        <div class="alert alert-warning alert-dismissable">
             <%= message %>
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          </div>
		<% end %>
  <% end %>

app/views/layouts/blocks/_sidebar.html.erb
<div class="text-center">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
</div>
<div class="side-bar-wrapper collapse navbar-collapse navbar-ex1-collapse">
  <a href="<%= root_path %>" class="logo hidden-sm hidden-xs">
    <%= image_tag('logo.png', width: "100", alt: "Логотип") %>
    <span><%= @current_zone %></span>
  </a>
  <div class="search-box">
    <%= form_tag servers_path, {:method => 'get', :autocomplete => :off} do %>
      <%= text_field_tag :name, params[:name], :class => "form-control", :placeholder => "Наименование сервера" %>
    <% end %>
  </div>
  <ul class="side-menu side-menu-notifications">
    <li>
      <a href="<%= servers_path %>">
        <i class="icon-desktop"></i> Сервера
      </a>
    </li>
  </ul>
  <div class="relative-w">
    <ul class="side-menu">
      <li>
        <a href="<%= tape_libraries_path %>">
          <i class="icon-sun"></i> Ленточные библиотеки
        </a>
      </li>
      <li>
        <a href="<%= wifis_path %>">
          <i class="icon-rss"></i> Устройства WIFI
        </a>
      </li>
      <li>
        <a href="<%= blades_path %>">
          <i class="icon-building"></i> Блэйд центры
        </a>
      </li>
      <li>

      <li>
        <a href="<%= datastorages_path %>">
          <i class="icon-hdd"></i> Дисковые хранилища
        </a>
      </li>
      <li>


        <a href="<%= zones_path %>">
          <i class="icon-plane"></i> Зоны
        </a>
      </li>

      <li>
        <a href="<%= areas_path %>">
          <i class="icon-home"></i> Помещения
        </a>
      </li>

      <li>
        <a href="<%= dcats_path %>">
          <i class="icon-pencil"></i> Редактор
        </a>
      </li>

    </ul>


    <ul class="side-menu">
    <li>
      <a href="<%= infos_path %>">
        <i class="icon-book"></i> База знаний
      </a>
    </li>
	
	<li>
      <a href="<%= replace_parts_path %>">
        <i class="icon-truck"></i> Замена комплектующих
      </a>
    </li>
	
  </ul>

  </div>
</div>

app/views/layouts/blocks/_top_menu.html.erb
<div class="header-links hidden-xs">
  <!-- <a href="notifications.html"><i class="icon-comments"></i> User Alerts</a>
  <a href="#"><i class="icon-cog"></i> Settings</a> -->
  <% if user_signed_in? %>
  	 <a href="#"><i class="icon-user"></i> <%= current_user.displayname %></a>
  	<%= link_to raw("<i class=\"icon-signout\"></i> Выход"), destroy_user_session_path, :method => :delete %>
  <% end %>
</div>