config/routes.rb
RailsInventory::Application.routes.draw do

  resources :datastorages

  resources :replace_parts

  devise_for :users

  resources :infos

  resources :commutators

  resources :wifis

  resources :servers do
    get :export, on: :collection
  end

  resources :tape_libraries

  resources :areas do
    resources :rackspaces
  end

  resources :zones

  resources :dcats do
    resources :dcat_items
  end

  resources :blades do
    resources :parts
  end

  get "history" => "history#index"

  get "main/index"
 
  

  

   root :to => 'main#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/datastorage.rb
class Datastorage < ActiveRecord::Base
  attr_accessible :disks, :extenders, :inventory_num, :name, :rackspace_id, :status_id, :zone_id, :model_id

  
end

app/controllers/datastorages_controller.rb
class DatastoragesController < ApplicationController
  # GET /datastorages
  # GET /datastorages.json
  def index
    @datastorages = Datastorage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @datastorages }
    end
  end

  # GET /datastorages/1
  # GET /datastorages/1.json
  def show
    @datastorage = Datastorage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @datastorage }
    end
  end

  # GET /datastorages/new
  # GET /datastorages/new.json
  def new
    @datastorage = Datastorage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @datastorage }
    end
  end

  # GET /datastorages/1/edit
  def edit
    @datastorage = Datastorage.find(params[:id])
  end

  # POST /datastorages
  # POST /datastorages.json
  def create
    @datastorage = Datastorage.new(params[:datastorage])

    respond_to do |format|
      if @datastorage.save
        format.html { redirect_to @datastorage, notice: 'Datastorage was successfully created.' }
        format.json { render json: @datastorage, status: :created, location: @datastorage }
      else
        format.html { render action: "new" }
        format.json { render json: @datastorage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /datastorages/1
  # PUT /datastorages/1.json
  def update
    @datastorage = Datastorage.find(params[:id])

    respond_to do |format|
      if @datastorage.update_attributes(params[:datastorage])
        format.html { redirect_to @datastorage, notice: 'Datastorage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @datastorage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datastorages/1
  # DELETE /datastorages/1.json
  def destroy
    @datastorage = Datastorage.find(params[:id])
    @datastorage.destroy

    respond_to do |format|
      format.html { redirect_to datastorages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/datastorages_helper.rb
module DatastoragesHelper
end

app/views/datastorages/_form.html.erb
<%= simple_form_for(@datastorage) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :zone_id %>
    <%= f.input :rackspace_id %>
    <%= f.input :status_id, as: :boolean %>
    <%= f.input :extenders %>
    <%= f.input :disks %>
    <%= f.input :inventory_num %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/datastorages/edit.html.erb
<h1>Editing datastorage</h1>

<%= render 'form' %>

<%= link_to 'Show', @datastorage %> |
<%= link_to 'Back', datastorages_path %>

app/views/datastorages/index.html.erb
<h1>Listing datastorages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Zone</th>
    <th>Rackspace</th>
    <th>Status</th>
    <th>Extenders</th>
    <th>Disks</th>
    <th>Inventory num</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @datastorages.each do |datastorage| %>
  <tr>
    <td><%= datastorage.name %></td>
    <td><%= datastorage.zone_id %></td>
    <td><%= datastorage.rackspace_id %></td>
    <td><%= datastorage.status_id %></td>
    <td><%= datastorage.extenders %></td>
    <td><%= datastorage.disks %></td>
    <td><%= datastorage.inventory_num %></td>
    <td><%= link_to 'Show', datastorage %></td>
    <td><%= link_to 'Edit', edit_datastorage_path(datastorage) %></td>
    <td><%= link_to 'Destroy', datastorage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Datastorage', new_datastorage_path %>

app/views/datastorages/new.html.erb
<h1>New datastorage</h1>

<%= render 'form' %>

<%= link_to 'Back', datastorages_path %>

app/views/datastorages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @datastorage.name %>
</p>

<p>
  <b>Zone:</b>
  <%= @datastorage.zone_id %>
</p>

<p>
  <b>Rackspace:</b>
  <%= @datastorage.rackspace_id %>
</p>

<p>
  <b>Status:</b>
  <%= @datastorage.status_id %>
</p>

<p>
  <b>Extenders:</b>
  <%= @datastorage.extenders %>
</p>

<p>
  <b>Disks:</b>
  <%= @datastorage.disks %>
</p>

<p>
  <b>Inventory num:</b>
  <%= @datastorage.inventory_num %>
</p>


<%= link_to 'Edit', edit_datastorage_path(@datastorage) %> |
<%= link_to 'Back', datastorages_path %>